
replicaCount: 1
name: pgadmin

image:
  repository: dpage/pgadmin4
  pullPolicy: IfNotPresent
  tag: "8.14"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

existingSecretPgadmin: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations:
  sidecar.istio.io/inject: "true"

podLabels:
  app: pgadmin
  app.kubernetes.io/name: pgadmin
  app.kubernetes.io/component: database-management

podSecurityContext:
  runAsUser: 5050
  runAsGroup: 5050
  fsGroup: 5050

securityContext: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: pgadmin.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

persistence:
  enabled: false

serverDefinitions:
  enabled: true
  servers:
    core_project:
      Name: "Core Project DB"
      Group: "CRUD Cluster"
      Host: "postgres-crud-rw.visiobook-namespace.svc.cluster.local"
      Port: 5432
      Username: "core_project_app"
      SSLMode: "prefer"
      MaintenanceDB: "core_project"
    core_user:
      Name: "Core User DB"
      Group: "CRUD Cluster"
      Host: "postgres-crud-rw.visiobook-namespace.svc.cluster.local"
      Port: 5432
      Username: "core_user_app"
      SSLMode: "prefer"
      MaintenanceDB: "core_user"
    analysis:
      Name: "Analysis DB"
      Group: "IO Cluster"
      Host: "postgres-io-rw.visiobook-namespace.svc.cluster.local"
      Port: 5432
      Username: "analysis_user"
      SSLMode: "prefer"
      MaintenanceDB: "analysis"
    ingestion:
      Name: "Ingestion DB"
      Group: "IO Cluster"
      Host: "postgres-io-rw.visiobook-namespace.svc.cluster.local"
      Port: 5432
      Username: "ingestion_user"
      SSLMode: "prefer"
      MaintenanceDB: "ingestion"
    storage:
      Name: "Storage DB"
      Group: "IO Cluster"
      Host: "postgres-io-rw.visiobook-namespace.svc.cluster.local"
      Port: 5432
      Username: "storage_user"
      SSLMode: "prefer"
      MaintenanceDB: "storage"


startupProbe:
  httpGet:
    path: /misc/ping
    port: http
  initialDelaySeconds: 10
  periodSeconds: 5
  timeoutSeconds: 5
  failureThreshold: 60

livenessProbe:
  httpGet:
    path: /misc/ping
    port: http
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /misc/ping
    port: http
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}

