apiVersion: v1
kind: ServiceAccount
metadata:
  name: ci-deployer
  namespace: visiobook-namespace
  labels:
    app: ci-deployer
    purpose: github-actions
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ci-deployer-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: ci-deployer
    namespace: visiobook-namespace
---
apiVersion: v1
kind: Secret
metadata:
  name: ci-deployer-token
  namespace: visiobook-namespace
  annotations:
    kubernetes.io/service-account.name: ci-deployer
type: kubernetes.io/service-account-token
