apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-user-secret
  namespace: visiobook-namespace
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  labels:
    app: pgadmin
type: Opaque
stringData:
  defaultEmail: "pgadmin@visiobook.cloud"
  defaultPassword: "oe#53AN[)8U6A{)5b@~2_8[H"


