{{- if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "minio.fullname" . }}
  labels:
    {{- include "minio.labels" . | nindent 4 }}
spec:
  hosts:
    - {{ include "minio.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
  http:
    - match:
        - port: {{ .Values.service.port }}
      route:
        - destination:
            host: {{ include "minio.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
            port:
              number: {{ .Values.service.port }}
    - match:
        - port: {{ .Values.service.consolePort }}
      route:
        - destination:
            host: {{ include "minio.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
            port:
              number: {{ .Values.service.consolePort }}
{{- end }}
