{{- if .Values.minio.defaultBuckets }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "minio.fullname" . }}-create-buckets
  labels:
    {{- include "minio.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  backoffLimit: 5
  template:
    metadata:
      labels:
        {{- include "minio.selectorLabels" . | nindent 8 }}
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      restartPolicy: OnFailure
      containers:
        - name: create-buckets
          image: minio/mc:latest
          command:
            - /bin/sh
            - /scripts/create-buckets.sh
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "minio.secretName" . }}
                  key: root-user
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "minio.secretName" . }}
                  key: root-password
          volumeMounts:
            - name: scripts
              mountPath: /scripts
      volumes:
        - name: scripts
          configMap:
            name: {{ include "minio.fullname" . }}-config
            defaultMode: 0755
{{- end }}
