---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://istio-release.storage.googleapis.com/charts
    targetRevision: 1.20.0
    chart: istiod
    helm:
      values: |
        telemetry:
          enabled: true
        pilot:
          traceSampling: 20
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 77.0.1
    chart: kube-prometheus-stack
    helm:
      values: |
        global:
          rbacCreate: true
        prometheusOperator:
          createCustomResource: true
        grafana:
          enabled: false
        prometheus:
          service:
            type: ClusterIP
          prometheusSpec:
            storageSpec:
              emptyDir: {}  # no persistent volume
            enableAdminAPI: true
        alertmanager:
          alertmanagerSpec:
            storage:
              emptyDir: {}  # no persistent volume
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kiali
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://kiali.org/helm-charts
    targetRevision: 1.82.0
    chart: kiali-server
    helm:
      values: |
        auth:
          strategy: anonymous
        external_services:
          prometheus:
            url: http://prometheus-kube-prometheus-prometheus.istio-system.svc.cluster.local:9090
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 6.60.6
    chart: grafana
    helm:
      values: |
        persistence:
          enabled: false
        service:
          type: ClusterIP
        adminUser: admin
        adminPassword: admin
        datasources:
          datasources.yaml:
            apiVersion: 1
            datasources:
              - name: Prometheus
                type: prometheus
                access: proxy
                url: http://prometheus-kube-prometheus-prometheus.istio-system.svc.cluster.local:9090
                isDefault: true
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
