apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kiali
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://kiali.org/helm-charts
    targetRevision: 1.82.0   # pick version compatible with your Istio
    chart: kiali-server
    helm:
      values: |
        auth:
          strategy: anonymous   # for testing; use proper auth in prod
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
