apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-test
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: ghcr.io/visiobook-esp/core-api-gateway
    argocd-image-updater.argoproj.io/core-api-gateway.update-strategy: latest
    argocd-image-updater.argoproj.io/write-back-method: git
spec:
  project: default
  source:
    repoURL: https://github.com/VisioBook-ESP/infra-helm-charts.git
    targetRevision: main  # or your actual branch
    path: environnement/dev/charts/nginx-test
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
