apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-test
  namespace: argocd
  annotations:
    # Correct digest strategy configuration - must specify the exact tag
    argocd-image-updater.argoproj.io/image-list: myapp=ghcr.io/visiobook-esp/repo-test-infra-dev:latest
    argocd-image-updater.argoproj.io/myapp.update-strategy: digest
    argocd-image-updater.argoproj.io/write-back-method: argocd
    argocd-image-updater.argoproj.io/myapp.force-update: "true"
    argocd-image-updater.argoproj.io/log.level: debug

spec:
  project: default
  source:
    repoURL: https://github.com/VisioBook-ESP/infra-helm-charts.git
    targetRevision: main
    path: environnement/dev/charts/nginx-test
    helm:
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true