apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pgadmin.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pgadmin.labels" . | nindent 4 }}
type: Opaque
data:
  default-email: {{ .Values.pgadmin.defaultEmail | b64enc | quote }}
  default-password: {{ .Values.pgadmin.defaultPassword | b64enc | quote }}

