apiVersion: v2
name: istio-custom
description: A Helm chart to deploy Istio base, istiod, and gateway
version: 0.1.0
dependencies:
  - name: base
    alias: istio-base
    version: 1.26.3
    repository: https://istio-release.storage.googleapis.com/charts
  - name: istiod
    version: 1.26.3
    repository: https://istio-release.storage.googleapis.com/charts
  - name: gateway
    alias: istio-ingress
    version: 1.26.3
    repository: https://istio-release.storage.googleapis.com/charts
