name: Helm Lint

on:
  push:
  pull_request:

jobs:
  lint:
    name: Lint all Helm charts
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.14.0

      - name: Lint all charts
        run: |
          helm lint environnement/dev/charts/* --strict
