name: Helm Unit Tests

on:
  push:
    paths:
      - 'charts/**'
      - '.github/workflows/helm-unittest.yml'
  pull_request:
    paths:
      - 'charts/**'
      - '.github/workflows/helm-unittest.yml'

jobs:
  org-runner-test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "✅ Running on organization-level self-hosted runner!"
  test:
    name: Run helm-unittest on all charts
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.14.0

      - name: Install helm-unittest plugin
        run: helm plugin install https://github.com/helm-unittest/helm-unittest

      - name: Run unit tests on all charts
        run: |
          for chart in charts/*; do
            [ -f "$chart/Chart.yaml" ] && echo "📦 Testing chart: $chart" && helm unittest "$chart" || exit 1
          done
